### ISSUE TITLE
Request body rewrite

### ISSUE THREAD

**Issue by esphen** [esphen/RESTED#106]
The request body part of the form needs some love. This tracking issue will be the main discussion thread and point of information for this new feature.

- [x] Create a dropdown with more presets. The following presets should be supported:
  - `application/json`
  - `application/x-www-form-urlencoded`
  - `multipart/form-data`
  - Raw body
  - More?
- [x] Have a more sane default than `multipart/form-data`. Probably `application/json`. Feel free to discuss below (#103)
- [x] Persist the user's previously selected preset (#88)
- [x] Make the body expanded by default on methods that support it (#78)
- [x] Show `Content-Type` header in the headers list when using a preset (#75)
